#!/usr/bin/env bash
sv=$1
#export sv=192.168.0.40
hn=$(ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1' | grep -v 172*)
echo "Client $hn connecting to server $sv"
export ROS_IP=$hn
export ROS_HOSTNAME=$hn
export ROS_MASTER_URI="http://$sv:11311"
rosrun jebediah_control controller


