jebediah:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position controllers ---------------------------------------
  servo_coxa_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: servo_coxa_1
    pid: {p: 100.0, i: 0.01, d: 10.0}
  servo_femur_1_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: servo_femur_1_1
    pid: {p: 100.0, i: 0.01, d: 10.0}
  servo_femur_1_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: servo_femur_1_2
    pid: {p: 100.0, i: 0.01, d: 10.0}
